<?php
if(!defined('CAN_RUN')) {
	exit('Access Denied');
}
$_priority[0]=array(
				'index'=>array(
						'index','menu','main','createrdpfile','tool_list','upload_tool','tool_down','changerole','do_devices_cache','get_sms','tool_delete','login_tip','chpwd','chpwd_save','login_user_field','qrcode','doqrcode','documentupload','dodocumentupload','documentlist','documentdel','getdocument','notice_tip','accept','doaccept'
					),
				'monitor'=>array(
						'index','status_image','system_monitor','network_monitor','apache_monitor','apache_monitor_edit','apache_monitor_save','mysql_monitor','mysql_monitor_edit','mysql_monitor_save','tomcat_monitor','tomcat_monitor_edit','tomcat_monitor_save','nginx_monitor','nginx_monitor_edit','nginx_monitor_save','interface_image','oracle_tablespace_monitor','oracle_tablespace_monitor_edit','oracle_tablespace_monitor_save','oracle_disk_monitor','oracle_disk_monitor_edit','oracle_disk_monitor_save','oracle_diskgroup_monitor','oracle_diskgroup_monitor_edit','oracle_diskgroup_monitor_save','weixin_monitor','dns_monitor','dns_monitor_edit','dns_monitor_save'
					),
				'session'=>array(
						'index','replay','download','downloadfile','view','logindesc','showdesc','dodesc','logincommit','showcommit','docommit'
					),
				'sftp'=>array(
						'index','download','view','logindesc','dodesc'
					),
				'scp'=>array(
						'index','download','search'
					),
				'ftp'=>array(
						'index','download','view','logindesc','dodesc'
					),
				'rdp'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','dodesc','downloadplayfile'
					),
				'as400'=>array(
						'index','view','logindesc','dodesc'
					),
				'vnc'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','dodesc'
					),
				'x11'=>array(
						'index','inputview','logindesc','dodesc'
					),
				'apppub'=>array(
						'index','inputview','view','urlsearch','plsqlhistory','downloadplayfile','sqlview'
					),
				'login'=>array(
						'index','winlinlogin','delete_all','detail'
					),
				'detail'=>array(
						'index','hostleftmenu','hostview','ping','hostbytype','cisco_interface','parameters','ciscoindex','ciscoleftmenu','ciscoview','eventlogs','appbytype','dev_login'
					),
				'authpriv'=>array(
						'index','winlinauthpriv','delete_all'
					),
				'eventlogs'=>array(
						'index','eventlogbyip','delete_all','detail','save','eventconfig','edit','applogs'
					),
				'thold'=>array(
						'index','snmp_server_policy_edit','snmp_server_policy_save','snmp_server_policy','snmp_server_policy_set','snmp_server_policy_set_save','snmp_server_policy_del','snmp_interface_policy','snmp_interface_policy_edit','snmp_interface_policy_save','snmp_interface_policy_set','snmp_interface_policy_set_save','snmp_interface_policy_del','status_thold_edit','status_thold_save','interface_thold_edit','interface_thold_save','app_thold_edit','app_thold_save','snmp_alert','snmp_alert_edit','snmp_alert_save','snmp_alert_del','snmp_status_warning_log','snmp_interface_log','app_warning_log','status_thold','status_thold_delete','interface_thold','interface_thold_delete','app_thold'
					),
				'pro'=>array(
						'dev_login','test_port','doinputauth','showinputauth','docommit','showcommit','dotwoauth','showtwoauth','dosmsauth','showsmsauth','generate_sms_code','editvncport','doeditvncport','showdesc','dodevdesc','gateone'
					),
				'workflow'=>array(
						'show_workflow_log','approvedesc','workflow_approve','workflow','workflow_edit','workflow_save','workflow_delete','workflow_approve','do_workflow_approve','workflow_close','search_sessions','workflow_new','workflow_new_save'
					),
				'member'=>array(
						'edit_self','save_self','user_disk','userdisk'
					),
				'commonuser'=>array(
						'directory','devices'
				)
				);

$_priority[1]=array(
				'index'=>array(
						'index','menu','main','tool_list','upload_tool','tool_down','tool_delete','license','upload_license','create_license','changerole','do_devices_cache','get_sms','tool_delete','login_tip','changelogo','login_user_field','qrcode','doqrcode','documentupload','dodocumentupload','documentlist','documentdel','getdocument','notice_tip'
					),
				'grouptree'=>array(
						'getchild','get_devgroup'
				),
				'session'=>array(
						'index','replay','download','downloadfile','view','logindesc','showdesc','dodesc','gateway_running_list','gateway_running_telnet','cut_running','monitor','search','search_html_log','search_html_log_download','logincommit','showcommit','docommit'
					),
				'sftp'=>array(
						'index','download','view','logindesc','showdesc','dodesc','search'
					),
				'scp'=>array(
						'index','download','search'
					),
				'ftp'=>array(
						'index','download','view','logindesc','showdesc','dodesc','search'
					),
				'rdp'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','showdesc','dodesc','downloadplayfile','search'
					),
				'rdprun'=>array(
						'index','del_session','cutoff'
					),
				'as400'=>array(
						'index','view','logindesc','showdesc','dodesc','search'
					),
				'vnc'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','showdesc','dodesc','search'
					),
				'vncrun'=>array(
						'index','del_session','cutoff','search'
					),
				'x11'=>array(
						'index','inputview','logindesc','showdesc','dodesc','search'
					),
				'apppub'=>array(
						'index','inputview','search','plsqlhistory','plsql_search','view','urlsearch','plsqlhistory','downloadplayfile','sqlview'
					),
				'apppubrun'=>array(
						'index'
					),
				'workflow'=>array(
						'workflow_contant','workflow_contant_delete','workflow_contant_edit','workflow_contant_save','show_workflow_log','approvedesc','workflow_approve','workflow','workflow_edit','workflow_save','workflow_delete','workflow_approve','do_workflow_approve','workflow_close','search_sessions'
					),
				'member'=>array(
						'index','edit_self','save_self','add','save','delete_all','delete','batchadd','batchadd_save','batchedit','batchedit_save','batchpriorityedit','batchpriorityeditsave','memberimport','domemberimport','radiususer','weektime','weektime_edit','weektime_save','delete_weektime','keys_index','showdesc','dodevdesc','importusbkey','doimportusbkey','loginlock','downloadca','edit','createca','online','offline','offline_all','showUsersByLevel','keybinduser','keybinduser_save','keys_delete','generateqrcode','cancelqrcode','regenerateqrcode','workdept','workdept_edit','workdept_delete','workdept_save','memberdesc','memberdesc_edit','memberdesc_delete','memberdesc_save','adconfig','adconfig_save'
					),
				'pro'=>array(
						'dev_index','dodevdesc','showdesc','dev_edit','dev_save','devbatchadd','batchdevsave','devbatchdel','dodevbatchdel','devpass_index','devpass_del','pass_edit','pass_save','pass_batchedit','pass_batchsave','dev_group','devgroup_edit','dev_group_save','dev_group_del','systemtype','systemtype_edit','systemtype_save','delete_systemtype','sshkey','sshkey_delete','sshkey_edit','sshkey_save','sshkey_list','sshkey_list_save','passwordkey','deletepasswordkey','async_account','async_config','sourceip','sourceip_delete','sourceip_edit','sourceip_save','resource_group','resource_group_edit','resource_group_save','dev_priority_search','app_priority_search','server_detect','passedit_selgroup','passedit_selgroup_save','passedit_seluser','passedit_seluser_save','resourcegroup_bind','resourcegrp_selgroup','resourcegrp_selgroup_save','resourcegrp_seluser','resourcegrp_seluser_save','resourcegroup_bindsave','resource_group_del','resource_group_import','resource_group_doimport','dev_del','viewradiusbind','sourceip_list','sourceip_list_edit','sourceiplist_save','sourceiplist_delete','export_resourcegroup','test_port','devimport','dodevimport','groupadddev','groupadddev_save','dev_delfromgroup','app_config_del','sshkey_import','sshkey_doimport','sshkey_export','sshkey_new','showpasswordkey','passwordkey_edit','passwordkey_save','password_cron','runupload','runchangepwd','runtongbu','accountlinux2devices','accountlinux_listacct','accountlinux_edit','accountlinux_save','devbatchloginlock','autofind','displayautofind','displayautofind_save','devbatchedit','dobatchdevsave','export_resourcegroup_priorty','resource_group_import_priorty','resource_group_doimport_priority','xzuser','batchserverpriorityedit','batchserverpriorityeditsave','batchdevicepriorityedit','batchdevicepriorityeditsave','groupbatchadd','groupbatchsave','sshkey_sync'
					),
				'reports'=>array(
						'index','systempriority_search','systempriority','apppriority_search','apppriority','systemaccount','appaccount','admin_log','logintims','loginacct','loginfailed','devloginreport','apploginreport','loginapproved','commandreport','cmdcachereport','cmdlistreport','appreport','sftpreport','ftpreport','dangercmdreport','dangercmdlistreport','reportgraph','host_reports','report_search','doreport_search','configreport','configreport_edit','configreport_save','cronreports','cronreport_del','cronreport_edit','cronreport_save','docronreports','downloadcronreport','cmdcache','cmdcache_edit','cmdcache_save','del_cmdcache','cmdcache_import','report_search_diy','report_search_diy_edit','doreport_search_diy_edit','configreport_delete','crontabreportsdelete','workflow_approve','app_reports','docronreports','dns_report','cmdlistreport_users','docmdlistreport_users','cmdlistreport_ips','docmdlistreport_ips','cmdlistreport_cmds','docmdlistreport_cmds','dangercmd','dangercmdsearch','maillog','maillog_del','aduserlog','aduserlog_del','cronreport_delete'
					),
				'config'=>array(
						'appserver_list','appserver_edit','appserver_save','appserver_delete','apppub_list','apppub_edit','apppub_delete','apppub_save','apppubimport','doapppubimport','apppubexport','appdevice_delete','default_policy','appprogram_list','appprogramimport','doappprogramimport','appicon_list','appicon_edit','appicon_save','appicon_delete','appprogram_edit','appprogram_save','appprogramexport','appprogram_delete','config_ssh','addldapserver','doaddldapserver','ldapusers','adusers','adusers_save','ssh_save','config_ftp','ntpset','ftp_save','sftp_save','ping_save','snmp_save','snmpcommunity_save','autodelete_save','keyedit','logintype','priority_cache_save','blankuser_save','ldap_save','certificate_save','async_save','login_times','login_save','ha','ha_save','syslog_mail_alarm','status_warning','loadbalance','loadbalance_edit','autochange_pwd','rdpinput_save','diskfull_save','threepripwd','dothreepripwd','threepripwd_twopwd','dothreepripwd_twopwd','viewthreepripwd_twopwd','doviewthreepripwd_twopwd','adusersbygroup','adimportconfig','adimportconfig_save','ldapusersbygroup','ldapimportconfig','ldapimportconfig_save','dpwdtime_save','rdprunning_save','loginauthtype_save','radiustolocal_save','rrdpauthtips_save','loginwrongtips_save','notice','notice_edit','notice_save','notice_del','asyncoutpass_save','ldapusers_save','passwordkey_save','accept_save','workflowadmin_save','rdpplayip_save','fingersecserver_save','chap_save','certs','certs_edit','certs_save','certs_del','certsreset'
					),
				'app'=>array(
						'applogin','applogin_save','app_group','app_group_edit','app_group_save','appresourcegroup_bind','appresourcegrp_selgroup','appresourcegrp_selgroup_save','appresourcegrp_seluser','appresourcegrp_seluser_save','appresourcegroup_bindsave','app_group_del','recopyhtml','recopy'
					),
				'ipacl'=>array(
						'index','loginpolicy','edit','save','delete','delete_policy','loginpolicy_edit'
					),
				'countlogs'=>array(
						'index','export','derivetoHTML','delete_all','graph','weekgraph','monthgraph'
					),
				'countlogin'=>array(
						'index','export','derivetoHTML','delete_all','week','month'
					),
				'system'=>array(
						'index','backup','refresh_host','truncate_alllogs','delete_table','audit_server2log_hosts','applog'
					),
				'search'=>array(
						'index','search','detail','export','do_export'
					),
				'status'=>array(
						'latest','system_alert','backup_session'
					),
				'backup'=>array(
						'index','recover','backup','backup_setting','backup_setting_del','backup_setting_edit','backup_setting_save','upgrade','doupgrade','backup_log','backup_log_del','cronjob','cronjob_audit','cronjob_mastslav','cronjob_autodelete','runupload','runchangepwd','runtongbu'
					),
				'eth'=>array(
						'serverstatus','downloadlog','vpnconfig','vpnconfig_save','vpn_list','route_list','vpn_edit','vpn_add','vpn_delete','route_edit','route_add','route_delete','ifcfgeth','config_eth','eth_save','config_route','route_add2','ping','tracepath','ifcfg_br','br0_save','route_save','network_restart','eth_del'
					),
				'vpnlog'=>array(
						'index','online','del','cut'
					),
				'alert'=>array(
						'index','config'
					),
				'monitor'=>array(
						'index','status_image','system_monitor','network_monitor','apache_monitor','apache_monitor_edit','apache_monitor_save','mysql_monitor','mysql_monitor_edit','mysql_monitor_save','tomcat_monitor','tomcat_monitor_edit','tomcat_monitor_save','nginx_monitor','nginx_monitor_edit','nginx_monitor_save','interface_image','oracle_tablespace_monitor','oracle_tablespace_monitor_edit','oracle_tablespace_monitor_save','oracle_disk_monitor','oracle_disk_monitor_edit','oracle_disk_monitor_save','oracle_diskgroup_monitor','oracle_diskgroup_monitor_edit','oracle_diskgroup_monitor_save','weixin_monitor','dns_monitor','dns_monitor_edit','dns_monitor_save'
					),
				'detail'=>array(
						'index','hostleftmenu','hostview','ping','hostbytype','cisco_interface','parameters','ciscoindex','ciscoleftmenu','ciscoview','eventlogs','appbytype','dev_login','status_backup','status_autorun'
					),
				'login'=>array(
						'index','winlinlogin','delete_all','detail','linux'
					),
				'authpriv'=>array(
						'index','winlinauthpriv','delete_all','linux'
					),
				'slaveserver'=>array(
						'index','edit','save','delete_all'
					),
				'eventlogs'=>array(
						'index','eventlogbyip','delete_all','detail','save','eventconfig','edit','applogs'
					),
				'thold'=>array(
						'index','snmp_server_policy_edit','snmp_server_policy_save','snmp_server_policy','snmp_server_policy_set','snmp_server_policy_set_save','snmp_server_policy_del','snmp_interface_policy','snmp_interface_policy_edit','snmp_interface_policy_save','snmp_interface_policy_set','snmp_interface_policy_set_save','snmp_interface_policy_del','status_thold_edit','status_thold_save','interface_thold_edit','interface_thold_save','app_thold_edit','app_thold_save','snmp_alert','snmp_alert_edit','snmp_alert_save','snmp_alert_del','snmp_status_warning_log','snmp_interface_log','app_warning_log','status_thold','status_thold_delete','interface_thold','interface_thold_delete','app_thold','app_thold_edit','app_thold_save','dns_thold','dns_thold_edit','dns_thold_save'
					),
				'configure'=>array(
						'snmp_interface','snmp_interface_edit','snmp_interface_save','snmp_interface_del'
					),
				'forbidden'=>array(
						'forbidden_groups_list','delete_all_gid','forbiddengps_edit','appserver_delete','apppub_list','apppub_edit','apppub_delete','apppub_save','apppubimport','doapppubimport','apppubexport','forbiddengps_cmd','forbiddengps_cmd_edit','forbiddengps_cmd_save','from_cmdgroup','from_cmdgroup_save','del_forbiddengps_cmd','cmdgroup_list','cmdgroup_cmd','cmdgroup_cmd_edit','cmdgroup_cmd_save','del_cmdgroup_cmd','forbiddengps_save','forbiddengps_group','cmdgroup_edit','cmdgroup_save','del_cmdgroup','del_forbiddengps','forbiddengps_user','forbiddengps_cmd_export','forbiddengps_cmd_import','forbiddengps_cmd_doimport'
					),
				'autorun'=>array(
						'autobackup_list','autobackup_save','autobackup_edit','autobackup_save','autobackup_save_backup','autobackup_dosave_backup','autobackup_dosave','viewfile','autotemplate','autotemplate_edit','autotemplate_save','autobackup_delete','viewtemplate','autotemplate_del','detail_config','detail_config_edit','detail_config_del','detail_config_save','autorun_result','auto_result','auto_result_file','auto_result_detail'
					),
				'autorunlog'=>array(
						'index','download','delete'
					),
				'systemNew'=>array(
						'index','systemNew_edit','save','import','do_import','export','applog_config','applog_config_edit','applog_config_save','applog_config_delete'
					),
				'log'=>array(
						'adminlog','delete_adminlog','logs_warning','applog_warning','logs_warning_detail','applog_warning_detail'
					)	
				);
$_priority[2]=array(
				'index'=>array(
						'index','menu','main','changerole','do_devices_cache','login_tip','login_user_field','qrcode','doqrcode','notice_tip'
					),
				'session'=>array(
						'index','replay','download','downloadfile','view','logindesc','showdesc','dodesc','gateway_running_list','gateway_running_telnet','cut_running','monitor','search','search_html_log','batch_del','autodelete','autodelete_edit','autodelete_save','search_html_log_download','search_html_log','logincommit','showcommit'
					),
				'sftp'=>array(
						'index','download','view','logindesc','showdesc','dodesc','search'
					),
				'ftp'=>array(
						'index','download','view','logindesc','showdesc','dodesc','search'
					),
				'scp'=>array(
						'index','download','search'
					),
				'rdp'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','showdesc','dodesc','downloadplayfile','search'
					),
				'rdprun'=>array(
						'index','del_session','search'
					),
				'as400'=>array(
						'index','view','logindesc','showdesc','dodesc','search'
					),
				'vnc'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','showdesc','dodesc','search'
					),
				'vncrun'=>array(
						'index','del_session','cutoff','search'
					),
				'x11'=>array(
						'index','inputview','logindesc','showdesc','dodesc','search'
					),
				'apppub'=>array(
						'index','inputview','search','view','urlsearch','plsql_search','plsqlhistory','downloadplayfile','sqlview'
					),
				'apppubrun'=>array(
						'index','search'
					),
				'workflow'=>array(
						'show_workflow_log','approvedesc','workflow_approve','workflow','workflow_edit','workflow_save','workflow_delete','workflow_approve','do_workflow_approve','workflow_close','search_sessions'
					),
				'member'=>array(
						'edit_self','save_self','user_disk'
					),
				'reports'=>array(
						'index','systempriority_search','systempriority','apppriority_search','apppriority','systemaccount','appaccount','admin_log','logintims','loginacct','loginfailed','devloginreport','apploginreport','loginapproved','commandreport','cmdcachereport','cmdlistreport','appreport','sftpreport','ftpreport','dangercmdreport','dangercmdlistreport','reportgraph','app_reports','workflow_approve','show_workflow_log','maillog','maillog_del'
					),
				'log'=>array(
						'adminlog','delete_adminlog','downuploaded','downloadfile'
					)						
				);
$_priority[3]=array(
				'index'=>array(
						'index','menu','main','tool_list','upload_tool','tool_down','changerole','do_devices_cache','login_tip','login_user_field','qrcode','doqrcode','documentupload','dodocumentupload','documentlist','documentdel','getdocument','notice_tip'
					),
				'grouptree'=>array(
						'getchild','get_devgroup'
				),
				'session'=>array(
						'index','replay','download','downloadfile','view','logindesc','showdesc','dodesc','gateway_running_list','gateway_running_telnet','cut_running','monitor','search','search_html_log','logincommit','showcommit'
					),
				'sftp'=>array(
						'index','download','view','logindesc','showdesc','dodesc','search'
					),
				'scp'=>array(
						'index','download','search'
					),
				'ftp'=>array(
						'index','download','view','logindesc','showdesc','dodesc','search'
					),
				'rdp'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','showdesc','dodesc','downloadplayfile','search'
					),
				'rdprun'=>array(
						'index','del_session','search'
					),
				'as400'=>array(
						'index','view','logindesc','showdesc','dodesc','search'
					),
				'vnc'=>array(
						'index','inputview','rdpmouse','clipboard','downloadfile','view','logindesc','showdesc','dodesc','search'
					),
				'vncrun'=>array(
						'index','del_session','cutoff','search'
					),
				'x11'=>array(
						'index','inputview','logindesc','showdesc','dodesc','search'
					),
				'apppub'=>array(
						'index','inputview','search','plsql_search','view','urlsearch','plsqlhistory','downloadplayfile','sqlview'
					),
				'apppubrun'=>array(
						'index','search'
					),
				'workflow'=>array(
						'workflow_contant','workflow_contant_delete','workflow_contant_edit','workflow_contant_save','show_workflow_log','approvedesc','workflow_approve','workflow','workflow_edit','workflow_save','workflow_delete','workflow_approve','do_workflow_approve','search_sessions'
					),
				'member'=>array(
						'index','edit_self','save_self','add','save','delete_all','delete','batchadd','batchadd_save','batchedit','batchedit_save','batchpriorityedit','batchpriorityeditsave','memberimport','domemberimport','radiususer','weektime','weektime_edit','weektime_save','loginlock','edit','createca','downloadca','delete_weektime','workdept','workdept_edit','workdept_delete','workdept_save'
					),
				'pro'=>array(
						'dev_index','dev_edit','dev_save','devbatchadd','batchdevsave','devbatchdel','dodevbatchdel','devpass_index','devpass_del','pass_edit','pass_save','pass_batchedit','pass_batchsave','dev_group','devgroup_edit','dev_group_save','dev_group_del','systemtype','systemtype_edit','systemtype_save','delete_systemtype','sshkey','sshkey_delete','sshkey_edit','sshkey_save','sshkey_list','sshkey_list_save','passwordkey','deletepasswordkey','async_account','sourceip','sourceip_delete','sourceip_edit','sourceip_save','resource_group','resource_group_edit','resource_group_save','dev_priority_search','app_priority_search','test_port','devimport','dodevimport','dev_del','sourceip_list','sourceip_list_edit','sourceiplist_save','sourceiplist_delete','app_config_del','resourcegroup_bind','resourcegroup_bindsave','showpasswordkey','showpwddownauth','dopwddownauth','dev_checkpass','dev_viewpass','logs_index','logs_statistic','resource_group_del','export_resourcegroup','resource_group_import','resource_group_doimport','passedit_seluser','passedit_seluser_save','devbatchloginlock','export_resourcegroup_priorty','resource_group_import_priorty','resource_group_doimport_priority','xzuser','batchserverpriorityedit','batchserverpriorityeditsave','batchdevicepriorityedit','batchdevicepriorityeditsave','groupbatchadd','groupbatchsave','autofind','displayautofind','passwordkey_edit','passwordkey_save'
					),
				'reports'=>array(
						'index','systempriority_search','systempriority','apppriority_search','apppriority','systemaccount','appaccount','admin_log','logintims','loginacct','loginfailed','devloginreport','apploginreport','loginapproved','commandreport','cmdcachereport','cmdlistreport','appreport','sftpreport','ftpreport','dangercmdreport','dangercmdlistreport','reportgraph','workflow_approve','show_workflow_log','maillog','maillog_del'
					),
				'config'=>array(
						'appserver_list','appserver_edit','appserver_save','appserver_delete','apppub_list','apppub_edit','apppub_delete','apppub_save','apppubimport','doapppubimport','apppubexport','appdevice_delete'
					),
				'app'=>array(
						'applogin','applogin_save','app_group','app_group_edit','app_group_save','appresourcegroup_bind','appresourcegrp_seluser','appresourcegrp_seluser_save','appresourcegrp_selgroup','appresourcegrp_selgroup_save','appresourcegroup_bindsave','app_group_del'
					),
				'ipacl'=>array(
						'loginpolicy','loginpolicy_edit','delete_policy'
					),
				'forbidden'=>array(
						'forbidden_groups_list','delete_all_gid','forbiddengps_edit','appserver_delete','apppub_list','apppub_edit','apppub_delete','apppub_save','apppubimport','doapppubimport','apppubexport','forbiddengps_save','forbiddengps_group','forbiddengps_user','forbiddengps_cmd','forbiddengps_cmd_edit','forbiddengps_cmd_save','from_cmdgroup','from_cmdgroup_save','del_forbiddengps_cmd','cmdgroup_edit','cmdgroup_save','del_cmdgroup','del_forbiddengps'
					),
				'autorun'=>array(
						'autobackup_list','autobackup_save','autobackup_dosave','viewfile','autotemplate','autotemplate_edit','autotemplate_save','autobackup_delete','viewtemplate','autotemplate_del','autobackup_save_backup','autobackup_dosave_backup','autobackup_dosave','viewfile','autotemplate','autotemplate_edit','autotemplate_save','autobackup_delete','viewtemplate','autotemplate_del','detail_config','detail_config_edit','detail_config_del','detail_config_save','autorun_result','auto_result','auto_result_file','auto_result_detail'
					),
				'detail'=>array(
						'index','hostleftmenu','hostview','ping','hostbytype','cisco_interface','parameters','ciscoindex','ciscoleftmenu','ciscoview','eventlogs','appbytype','dev_login'
					),
				'autorunlog'=>array(
						'index','delete','download'
					)
				);
$_priority[10]=array(
				'index'=>array(
						'index','menu','main','deletepassfile','dopassdown','passdown','do_devices_cache','changerole','do_devices_cache','login_tip','login_user_field','qrcode','doqrcode','notice_tip'
					),
				'pro'=>array(
						'index','showpwddownauth','dopwddownauth','dev_checkpass','passwordedit','password_cron','passwordcheck','logs_index','logs_del','dev_edit','dev_save','dev_viewpass','list_active_change','lac_save','lac_save2','logs_statistic','pass_edit','passedit_seluser','passedit_seluser_save','passedit_selgroup','passedit_selgroup_save','pass_save','devbatchloginlock','showdesc','dodesc'
					),
				'backup'=>array(
						'runupload','runchangepwd','runtongbu','backup_setting_forpassword','backup_setting_forpassword_del','backup_setting_forpassword_edit','backup_setting_forpassword_save'
					),
				'workflow'=>array(
						'workflow','show_workflow_log'
					),
				'member'=>array(
						'edit_self','save_self'
					),
				'detail'=>array(
						'index','hostleftmenu','hostview','ping','hostbytype','cisco_interface','parameters','ciscoindex','ciscoleftmenu','ciscoview','eventlogs','appbytype','dev_login'
					)					
				);
$_priority[4]=array(
				'index'=>array(
						'index','menu','main','tool_list','upload_tool','tool_down','tool_delete','license','upload_license','create_license','changerole','do_devices_cache','login_tip','login_user_field','qrcode','doqrcode','notice_tip'
					),
				'pro'=>array(
						'dev_index','dev_edit','dev_save','devbatchadd','batchdevsave','devbatchdel','dodevbatchdel','devpass_index','devpass_del','pass_edit','pass_save','pass_batchedit','pass_batchsave','dev_group','devgroup_edit','dev_group_save','dev_group_del','systemtype','systemtype_edit','systemtype_save','delete_systemtype','sshkey','sshkey_delete','sshkey_edit','sshkey_save','sshkey_list','sshkey_list_save','passwordkey','deletepasswordkey','async_account','sourceip','sourceip_delete','sourceip_edit','sourceip_save','resource_group','resource_group_edit','resource_group_save','dev_priority_search','app_priority_search','test_port','devimport','dodevimport','dev_del','sourceip_list','sourceip_list_edit','sourceiplist_save','sourceiplist_delete','resourcegroup_bind','resourcegroup_bindsave','resource_group_del','devbatchloginlock'
					),
				'member'=>array(
						'index','edit_self','save_self','add','save','delete_all','delete','batchadd','batchadd_save','batchedit','batchedit_save','batchpriorityedit','batchpriorityeditsave','memberimport','domemberimport','radiususer','weektime','weektime_edit','weektime_save','loginlock','edit','createca','downloadca','delete_weektime'
					),
				'config'=>array(
						'appserver_list','appserver_edit','appserver_save','appserver_delete','apppub_list','apppub_edit','apppub_delete','apppub_save','apppubimport','doapppubimport','apppubexport','appdevice_delete','default_policy','appprogram_list','appprogramimport','doappprogramimport','appicon_list','appicon_edit','appicon_save','appicon_delete','appprogram_edit','appprogram_save','appprogramexport','appprogram_delete','config_ssh','addldapserver','doaddldapserver','ldapusers','adusers','ssh_save','config_ftp','ntpset','ftp_save','sftp_save','ping_save','snmp_save','snmpcommunity_save','autodelete_save','keyedit','logintype','priority_cache_save','blankuser_save','ldap_save','certificate_save','async_save','login_times','login_save','ha','ha_save','syslog_mail_alarm','status_warning','loadbalance','loadbalance_edit','autochange_pwd','rdpinput_save','adimportconfig','adimportconfig_save'
					),
				'app'=>array(
						'applogin','applogin_save','app_group','app_group_edit','app_group_save','appresourcegroup_bind','appresourcegrp_selgroup','appresourcegrp_selgroup_save','appresourcegrp_seluser','appresourcegrp_seluser_save','appresourcegroup_bindsave','app_group_del'
					),
				'ipacl'=>array(
						'index','loginpolicy','edit','save','delete','delete_policy'
					),
				'autorun'=>array(
						'autobackup_list','autobackup_save','autobackup_dosave','viewfile','autotemplate','autotemplate_edit','autotemplate_save','autobackup_delete','viewtemplate','autotemplate_del'
					)
				);
$_priority[11]=array(
				'index'=>array(
						'index','menu','qrcode','doqrcode','notice_tip','tool_list','upload_tool','tool_down','tool_delete'
					),
				'member'=>array(
						'edit_self','save_self'
					)
				);
$_priority[21]=$_priority[3];
$_priority[101]=$_priority[3];
if(!(($controller=='c_admin_index'&&($action=='login'||$action=='logout'||$action=='chklogin'||$action=='get_sms'||$action=='jiekouyanz'||$action=='login_user_field'||$action=='get_user_login_fristauth'))||($controller=='c_admin_reports'&&$action=='docronreports')||($controller=='c_admin_config'&&$action=='synchronization_ad_users') ||($controller=='c_admin_interface'))){
	//if(intval($_SESSION['ADMIN_LEVEL'])===0){

		//var_dump($_SESSION);var_dump(substr($controller, strrpos($controller, '_')+1));var_dump($controller);var_dump($action);var_dump($_priority[1]['workflow']);
		$_is_power = $_priority[$_SESSION['ADMIN_LEVEL']][substr($controller, strrpos($controller, '_')+1)]&&in_array($action, $_priority[$_SESSION['ADMIN_LEVEL']][substr($controller, strrpos($controller, '_')+1)]);
		if(!$_is_power){
			echo 'no power';
			exit;
		}
	//}
}

?>